# Generated by Django 4.1.4 on 2022-12-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_interval_reservation_minutes', models.PositiveSmallIntegerField()),
                ('interval_price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.typeuser'),
        ),
    ]
