# Generated by Django 4.1.4 on 2022-12-14 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('min_time', models.TimeField(editable=False)),
                ('max_time', models.TimeField(editable=False)),
                ('interval_reservation', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
