# Generated by Django 4.1.4 on 2022-12-14 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationsettings',
            name='active_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservationsettings',
            name='interval_reservation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservationsettings',
            name='max_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservationsettings',
            name='min_time',
            field=models.TimeField(),
        ),
    ]
