# Generated by Django 4.1.4 on 2022-12-14 18:29

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservationsettings_interval_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationsettings',
            name='active_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de activación (active_date)'),
        ),
        migrations.AlterField(
            model_name='reservationsettings',
            name='interval_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'El precio del intervalo mínimo ("interval_price") de reserva no puede ser negativo')], verbose_name='Precio por intervalo de reserva (interval_price)'),
        ),
        migrations.AlterField(
            model_name='reservationsettings',
            name='interval_reservation_minutes',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'El intervalo mínimo ("interval_reservation_minutes") de reserva en minutos no puede ser inferior a 1')], verbose_name='Intervalo mínimo de reservas en minutos (interval_reservation_minutes)'),
        ),
        migrations.AlterField(
            model_name='reservationsettings',
            name='max_time',
            field=models.TimeField(verbose_name='Hora finalización de reservas (max_time)'),
        ),
        migrations.AlterField(
            model_name='reservationsettings',
            name='min_time',
            field=models.TimeField(verbose_name='Hora inicio de reservas (min_time)'),
        ),
    ]
