# Generated by Django 4.1.4 on 2022-12-14 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservationsettings_active_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationsettings',
            name='interval_price',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'El precio del intervalo mínimo ("interval_price") de reserva no puede ser negativo')], verbose_name='Precio por intervalo de reserva (interval_price)'),
        ),
    ]
