# Generated by Django 4.1.4 on 2022-12-14 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_reservationsettings_interval_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.reservationsettings'),
        ),
        migrations.AlterField(
            model_name='reservationsettings',
            name='active_date',
            field=models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Fecha de activación (active_date)'),
        ),
    ]
