# Generated by Django 4.1.4 on 2022-12-15 16:34

from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_reservation_reservation_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationsettings',
            name='max_time',
            field=models.TimeField(validators=[reservation.models.time_validator_seconds], verbose_name='Hora finalización de reservas (max_time)'),
        ),
        migrations.AlterField(
            model_name='reservationsettings',
            name='min_time',
            field=models.TimeField(validators=[reservation.models.time_validator_seconds], verbose_name='Hora inicio de reservas (min_time)'),
        ),
    ]
