# Generated by Django 4.1.4 on 2022-12-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_reservationsettings_max_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
