# Generated by Django 4.1.4 on 2022-12-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_information_alter_reservation_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
